// Antimetal API definitions
// Copyright Antimetal, Inc. All rights reserved.
//
// Use of this source code and APIs are governed by a source available license that can be found in
// the LICENSE file or at:
// https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: antimetal/agent/v1/instance.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SemanticVersion deconstructions the major, minor, and patch versions
// according to SemVer (https://semver.org)
type SemanticVersion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// semver major version
	Major uint32 `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	// semver minor version
	Minor uint32 `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	// semver patch version
	Patch         uint32 `protobuf:"varint,3,opt,name=patch,proto3" json:"patch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemanticVersion) Reset() {
	*x = SemanticVersion{}
	mi := &file_antimetal_agent_v1_instance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticVersion) ProtoMessage() {}

func (x *SemanticVersion) ProtoReflect() protoreflect.Message {
	mi := &file_antimetal_agent_v1_instance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticVersion.ProtoReflect.Descriptor instead.
func (*SemanticVersion) Descriptor() ([]byte, []int) {
	return file_antimetal_agent_v1_instance_proto_rawDescGZIP(), []int{0}
}

func (x *SemanticVersion) GetMajor() uint32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *SemanticVersion) GetMinor() uint32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

func (x *SemanticVersion) GetPatch() uint32 {
	if x != nil {
		return x.Patch
	}
	return 0
}

// Build contains information about the Antimetal Agent build.
type Build struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// version follows semver guidelines.
	Version *SemanticVersion `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// revision is the specific revision id that the build is based on (e.g. Git commit)
	Revision      string `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Build) Reset() {
	*x = Build{}
	mi := &file_antimetal_agent_v1_instance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Build) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Build) ProtoMessage() {}

func (x *Build) ProtoReflect() protoreflect.Message {
	mi := &file_antimetal_agent_v1_instance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Build.ProtoReflect.Descriptor instead.
func (*Build) Descriptor() ([]byte, []int) {
	return file_antimetal_agent_v1_instance_proto_rawDescGZIP(), []int{1}
}

func (x *Build) GetVersion() *SemanticVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *Build) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

// Instance identifies a running Antimetal Agent process.
type Instance struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is generated by the Agent and presented to the management server.
	// The generated id should adhere to the following requirements:
	//
	//   - MUST be 16 bytes long
	//   - MUST be follow the UUID v7 spec
	//
	// The id SHOULD remain unchanged for the lifetime of the Agent process.
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// build used for the running Antimetal Agent process.
	Build         *Build `protobuf:"bytes,2,opt,name=build,proto3" json:"build,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instance) Reset() {
	*x = Instance{}
	mi := &file_antimetal_agent_v1_instance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance) ProtoMessage() {}

func (x *Instance) ProtoReflect() protoreflect.Message {
	mi := &file_antimetal_agent_v1_instance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instance.ProtoReflect.Descriptor instead.
func (*Instance) Descriptor() ([]byte, []int) {
	return file_antimetal_agent_v1_instance_proto_rawDescGZIP(), []int{2}
}

func (x *Instance) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Instance) GetBuild() *Build {
	if x != nil {
		return x.Build
	}
	return nil
}

var File_antimetal_agent_v1_instance_proto protoreflect.FileDescriptor

const file_antimetal_agent_v1_instance_proto_rawDesc = "" +
	"\n" +
	"!antimetal/agent/v1/instance.proto\x12\x12antimetal.agent.v1\"S\n" +
	"\x0fSemanticVersion\x12\x14\n" +
	"\x05major\x18\x01 \x01(\rR\x05major\x12\x14\n" +
	"\x05minor\x18\x02 \x01(\rR\x05minor\x12\x14\n" +
	"\x05patch\x18\x03 \x01(\rR\x05patch\"b\n" +
	"\x05Build\x12=\n" +
	"\aversion\x18\x01 \x01(\v2#.antimetal.agent.v1.SemanticVersionR\aversion\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\tR\brevision\"K\n" +
	"\bInstance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12/\n" +
	"\x05build\x18\x02 \x01(\v2\x19.antimetal.agent.v1.BuildR\x05buildB\xd0\x01\n" +
	"\x16com.antimetal.agent.v1B\rInstanceProtoP\x01Z=github.com/antimetal/agent/pkg/api/antimetal/agent/v1;agentv1\xa2\x02\x03AAX\xaa\x02\x12Antimetal.Agent.V1\xca\x02\x12Antimetal\\Agent\\V1\xe2\x02\x1eAntimetal\\Agent\\V1\\GPBMetadata\xea\x02\x14Antimetal::Agent::V1b\x06proto3"

var (
	file_antimetal_agent_v1_instance_proto_rawDescOnce sync.Once
	file_antimetal_agent_v1_instance_proto_rawDescData []byte
)

func file_antimetal_agent_v1_instance_proto_rawDescGZIP() []byte {
	file_antimetal_agent_v1_instance_proto_rawDescOnce.Do(func() {
		file_antimetal_agent_v1_instance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_antimetal_agent_v1_instance_proto_rawDesc), len(file_antimetal_agent_v1_instance_proto_rawDesc)))
	})
	return file_antimetal_agent_v1_instance_proto_rawDescData
}

var file_antimetal_agent_v1_instance_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_antimetal_agent_v1_instance_proto_goTypes = []any{
	(*SemanticVersion)(nil), // 0: antimetal.agent.v1.SemanticVersion
	(*Build)(nil),           // 1: antimetal.agent.v1.Build
	(*Instance)(nil),        // 2: antimetal.agent.v1.Instance
}
var file_antimetal_agent_v1_instance_proto_depIdxs = []int32{
	0, // 0: antimetal.agent.v1.Build.version:type_name -> antimetal.agent.v1.SemanticVersion
	1, // 1: antimetal.agent.v1.Instance.build:type_name -> antimetal.agent.v1.Build
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_antimetal_agent_v1_instance_proto_init() }
func file_antimetal_agent_v1_instance_proto_init() {
	if File_antimetal_agent_v1_instance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_antimetal_agent_v1_instance_proto_rawDesc), len(file_antimetal_agent_v1_instance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_antimetal_agent_v1_instance_proto_goTypes,
		DependencyIndexes: file_antimetal_agent_v1_instance_proto_depIdxs,
		MessageInfos:      file_antimetal_agent_v1_instance_proto_msgTypes,
	}.Build()
	File_antimetal_agent_v1_instance_proto = out.File
	file_antimetal_agent_v1_instance_proto_goTypes = nil
	file_antimetal_agent_v1_instance_proto_depIdxs = nil
}
