apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service_account.yaml
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
- metrics_auth_role.yaml
- metrics_auth_role_binding.yaml
- metrics_reader_role.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubererntes.io/component: rbac
      app.kubernetes.io/part-of: antimetal
