apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: antimetal-leader-election-rolebinding
  name: antimetal-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: antimetal-leader-election-role
subjects:
- kind: ServiceAccount
  name: agent
