apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: metrics-reader
  name: antimetal-metrics-reader
rules:
- nonResourceURLs:
  - "/metrics"
  verbs:
  - get
