apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: agent-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: antimetal
    app.kubernetes.io/part-of: antimetal
    app.kubernetes.io/managed-by: kustomize
  name: agent-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: agent-role
subjects:
- kind: ServiceAccount
  name: agent
  namespace: system
