apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: agent-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: antimetal
    app.kubernetes.io/part-of: antimetal
    app.kubernetes.io/managed-by: kustomize
  name: agent
  namespace: system
