// Antimetal API definitions
// Copyright Antimetal, Inc. All rights reserved.
//
// Use of this source code and APIs are governed by a source available license that can be found in
// the LICENSE file or at:
// https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: antimetal/types/v1/types.proto

package typesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TypeDescriptor describes an object type.
type TypeDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kind type full url (e.g. resource.v1.Resource, resource.v1.Relationship, etc.).
	// It represents the Kind for type.
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// type should be the full url
	Type          string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeDescriptor) Reset() {
	*x = TypeDescriptor{}
	mi := &file_antimetal_types_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeDescriptor) ProtoMessage() {}

func (x *TypeDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_antimetal_types_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeDescriptor.ProtoReflect.Descriptor instead.
func (*TypeDescriptor) Descriptor() ([]byte, []int) {
	return file_antimetal_types_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *TypeDescriptor) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *TypeDescriptor) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_antimetal_types_v1_types_proto protoreflect.FileDescriptor

const file_antimetal_types_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x1eantimetal/types/v1/types.proto\x12\x12antimetal.types.v1\"8\n" +
	"\x0eTypeDescriptor\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04typeB\xcd\x01\n" +
	"\x16com.antimetal.types.v1B\n" +
	"TypesProtoP\x01Z=github.com/antimetal/agent/pkg/api/antimetal/types/v1;typesv1\xa2\x02\x03ATX\xaa\x02\x12Antimetal.Types.V1\xca\x02\x12Antimetal\\Types\\V1\xe2\x02\x1eAntimetal\\Types\\V1\\GPBMetadata\xea\x02\x14Antimetal::Types::V1b\x06proto3"

var (
	file_antimetal_types_v1_types_proto_rawDescOnce sync.Once
	file_antimetal_types_v1_types_proto_rawDescData []byte
)

func file_antimetal_types_v1_types_proto_rawDescGZIP() []byte {
	file_antimetal_types_v1_types_proto_rawDescOnce.Do(func() {
		file_antimetal_types_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_antimetal_types_v1_types_proto_rawDesc), len(file_antimetal_types_v1_types_proto_rawDesc)))
	})
	return file_antimetal_types_v1_types_proto_rawDescData
}

var file_antimetal_types_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_antimetal_types_v1_types_proto_goTypes = []any{
	(*TypeDescriptor)(nil), // 0: antimetal.types.v1.TypeDescriptor
}
var file_antimetal_types_v1_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_antimetal_types_v1_types_proto_init() }
func file_antimetal_types_v1_types_proto_init() {
	if File_antimetal_types_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_antimetal_types_v1_types_proto_rawDesc), len(file_antimetal_types_v1_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_antimetal_types_v1_types_proto_goTypes,
		DependencyIndexes: file_antimetal_types_v1_types_proto_depIdxs,
		MessageInfos:      file_antimetal_types_v1_types_proto_msgTypes,
	}.Build()
	File_antimetal_types_v1_types_proto = out.File
	file_antimetal_types_v1_types_proto_goTypes = nil
	file_antimetal_types_v1_types_proto_depIdxs = nil
}
