// Antimetal API definitions
// Copyright Antimetal, Inc. All rights reserved.
//
// Use of this source code and APIs are governed by a source available license that can be found in
// the LICENSE file or at:
// https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: antimetal/service/agent/v1/service.proto

package agentv1

import (
	v1 "github.com/antimetal/agent/pkg/api/antimetal/agent/v1"
	v12 "github.com/antimetal/agent/pkg/api/antimetal/runtime/v1"
	v11 "github.com/antimetal/agent/pkg/api/antimetal/types/v1"
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WatchConfigRequestType defines the different types of requests an agent
// can send in the configuration watch stream.
type WatchConfigRequestType int32

const (
	// INITIAL request is sent by the agent when first establishing the stream.
	// This request MUST include the agent's instance information and supported
	// collector capabilities. It MAY include existing configuration objects
	// the agent currently has to enable incremental updates.
	WatchConfigRequestType_WATCH_CONFIG_REQUEST_TYPE_INITIAL WatchConfigRequestType = 0
	// ACK (acknowledgment) indicates the agent successfully received and applied
	// the configuration from the server. The agent MUST include the sequence
	// number of the response being acknowledged.
	WatchConfigRequestType_WATCH_CONFIG_REQUEST_TYPE_ACK WatchConfigRequestType = 1
	// NACK (negative acknowledgment) indicates the agent failed to apply the
	// configuration from the server. The agent MUST include the sequence number
	// and error details explaining why the configuration was rejected.
	WatchConfigRequestType_WATCH_CONFIG_REQUEST_TYPE_NACK WatchConfigRequestType = 2
)

// Enum value maps for WatchConfigRequestType.
var (
	WatchConfigRequestType_name = map[int32]string{
		0: "WATCH_CONFIG_REQUEST_TYPE_INITIAL",
		1: "WATCH_CONFIG_REQUEST_TYPE_ACK",
		2: "WATCH_CONFIG_REQUEST_TYPE_NACK",
	}
	WatchConfigRequestType_value = map[string]int32{
		"WATCH_CONFIG_REQUEST_TYPE_INITIAL": 0,
		"WATCH_CONFIG_REQUEST_TYPE_ACK":     1,
		"WATCH_CONFIG_REQUEST_TYPE_NACK":    2,
	}
)

func (x WatchConfigRequestType) Enum() *WatchConfigRequestType {
	p := new(WatchConfigRequestType)
	*p = x
	return p
}

func (x WatchConfigRequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WatchConfigRequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_antimetal_service_agent_v1_service_proto_enumTypes[0].Descriptor()
}

func (WatchConfigRequestType) Type() protoreflect.EnumType {
	return &file_antimetal_service_agent_v1_service_proto_enumTypes[0]
}

func (x WatchConfigRequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WatchConfigRequestType.Descriptor instead.
func (WatchConfigRequestType) EnumDescriptor() ([]byte, []int) {
	return file_antimetal_service_agent_v1_service_proto_rawDescGZIP(), []int{0}
}

// WatchConfigRequest is sent by agents to the management server in the
// configuration watch stream. The request type determines which fields
// are required and how the server should interpret the message.
type WatchConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// instance identifies the Antimetal Agent making the request.
	// This field is REQUIRED for INITIAL requests and SHOULD be included
	// in subsequent requests for server-side correlation and debugging.
	Instance *v1.Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	// type specifies the purpose of this request message.
	// This field is REQUIRED for all request types.
	Type WatchConfigRequestType `protobuf:"varint,2,opt,name=type,proto3,enum=antimetal.service.agent.v1.WatchConfigRequestType" json:"type,omitempty"`
	// supported_collectors is a list of collector values indicating which data
	// collectors this agent supports. This field is REQUIRED for INITIAL requests.
	SupportedCollectors []v1.Collectors `protobuf:"varint,3,rep,packed,name=supported_collectors,json=supportedCollectors,proto3,enum=antimetal.agent.v1.Collectors" json:"supported_collectors,omitempty"`
	// initial_configs contains configuration objects the agent currently has.
	// This field is OPTIONAL and only used with INITIAL requests to enable
	// incremental configuration updates. The server can compare these with
	// the desired state and send only necessary changes. Each object wraps
	// a specific config type.
	InitialConfigs []*v11.Object `protobuf:"bytes,4,rep,name=initial_configs,json=initialConfigs,proto3" json:"initial_configs,omitempty"`
	// linux_runtime provides Linux-specific runtime information from the agent.
	// such as kernel version and cgroup configuration. The agent can send this
	// during an INITIAL request. The server uses this information to optimize
	// configuration delivery and ensure compatibility with the agent's runtime
	// environment.
	LinuxRuntime *v12.Linux `protobuf:"bytes,5,opt,name=linux_runtime,json=linuxRuntime,proto3" json:"linux_runtime,omitempty"`
	// response_seq_num is the sequence number of the server response being
	// acknowledged or rejected. This field is REQUIRED for ACK and NACK
	// request types and MUST be empty for INITIAL requests.
	ResponseSeqNum string `protobuf:"bytes,6,opt,name=response_seq_num,json=responseSeqNum,proto3" json:"response_seq_num,omitempty"`
	// error_detail provides information about why a configuration was rejected.
	// This field is REQUIRED for NACK requests and MUST be empty for other
	// request types. The error should be detailed enough for server-side
	// debugging and corrective action.
	ErrorDetail   *status.Status `protobuf:"bytes,7,opt,name=error_detail,json=errorDetail,proto3" json:"error_detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchConfigRequest) Reset() {
	*x = WatchConfigRequest{}
	mi := &file_antimetal_service_agent_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchConfigRequest) ProtoMessage() {}

func (x *WatchConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_antimetal_service_agent_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchConfigRequest.ProtoReflect.Descriptor instead.
func (*WatchConfigRequest) Descriptor() ([]byte, []int) {
	return file_antimetal_service_agent_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *WatchConfigRequest) GetInstance() *v1.Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *WatchConfigRequest) GetType() WatchConfigRequestType {
	if x != nil {
		return x.Type
	}
	return WatchConfigRequestType_WATCH_CONFIG_REQUEST_TYPE_INITIAL
}

func (x *WatchConfigRequest) GetSupportedCollectors() []v1.Collectors {
	if x != nil {
		return x.SupportedCollectors
	}
	return nil
}

func (x *WatchConfigRequest) GetInitialConfigs() []*v11.Object {
	if x != nil {
		return x.InitialConfigs
	}
	return nil
}

func (x *WatchConfigRequest) GetLinuxRuntime() *v12.Linux {
	if x != nil {
		return x.LinuxRuntime
	}
	return nil
}

func (x *WatchConfigRequest) GetResponseSeqNum() string {
	if x != nil {
		return x.ResponseSeqNum
	}
	return ""
}

func (x *WatchConfigRequest) GetErrorDetail() *status.Status {
	if x != nil {
		return x.ErrorDetail
	}
	return nil
}

// WatchConfigResponse is sent by the management server to agents with
// configuration updates and control information.
type WatchConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// configs contains the configuration objects being delivered to the agent.
	// Each object wraps a specific config message type (e.g., HostStatsCollectionConfig)
	Configs []*v11.Object `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	// seq_num is a server-assigned sequence number for this response.
	// Sequence numbers MUST be monotonically increasing within a stream
	// and are used by agents to acknowledge specific configuration deliveries.
	// This field is REQUIRED for all responses containing configuration data.
	SeqNum        string `protobuf:"bytes,2,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchConfigResponse) Reset() {
	*x = WatchConfigResponse{}
	mi := &file_antimetal_service_agent_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchConfigResponse) ProtoMessage() {}

func (x *WatchConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_antimetal_service_agent_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchConfigResponse.ProtoReflect.Descriptor instead.
func (*WatchConfigResponse) Descriptor() ([]byte, []int) {
	return file_antimetal_service_agent_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *WatchConfigResponse) GetConfigs() []*v11.Object {
	if x != nil {
		return x.Configs
	}
	return nil
}

func (x *WatchConfigResponse) GetSeqNum() string {
	if x != nil {
		return x.SeqNum
	}
	return ""
}

var File_antimetal_service_agent_v1_service_proto protoreflect.FileDescriptor

const file_antimetal_service_agent_v1_service_proto_rawDesc = "" +
	"\n" +
	"(antimetal/service/agent/v1/service.proto\x12\x1aantimetal.service.agent.v1\x1a\x1fantimetal/agent/v1/config.proto\x1a!antimetal/agent/v1/instance.proto\x1a antimetal/runtime/v1/linux.proto\x1a\x1eantimetal/types/v1/types.proto\x1a\x17google/rpc/status.proto\"\xd1\x03\n" +
	"\x12WatchConfigRequest\x128\n" +
	"\binstance\x18\x01 \x01(\v2\x1c.antimetal.agent.v1.InstanceR\binstance\x12F\n" +
	"\x04type\x18\x02 \x01(\x0e22.antimetal.service.agent.v1.WatchConfigRequestTypeR\x04type\x12Q\n" +
	"\x14supported_collectors\x18\x03 \x03(\x0e2\x1e.antimetal.agent.v1.CollectorsR\x13supportedCollectors\x12C\n" +
	"\x0finitial_configs\x18\x04 \x03(\v2\x1a.antimetal.types.v1.ObjectR\x0einitialConfigs\x12@\n" +
	"\rlinux_runtime\x18\x05 \x01(\v2\x1b.antimetal.runtime.v1.LinuxR\flinuxRuntime\x12(\n" +
	"\x10response_seq_num\x18\x06 \x01(\tR\x0eresponseSeqNum\x125\n" +
	"\ferror_detail\x18\a \x01(\v2\x12.google.rpc.StatusR\verrorDetail\"d\n" +
	"\x13WatchConfigResponse\x124\n" +
	"\aconfigs\x18\x01 \x03(\v2\x1a.antimetal.types.v1.ObjectR\aconfigs\x12\x17\n" +
	"\aseq_num\x18\x02 \x01(\tR\x06seqNum*\x86\x01\n" +
	"\x16WatchConfigRequestType\x12%\n" +
	"!WATCH_CONFIG_REQUEST_TYPE_INITIAL\x10\x00\x12!\n" +
	"\x1dWATCH_CONFIG_REQUEST_TYPE_ACK\x10\x01\x12\"\n" +
	"\x1eWATCH_CONFIG_REQUEST_TYPE_NACK\x10\x022\x8e\x01\n" +
	"\x16AgentManagementService\x12t\n" +
	"\vWatchConfig\x12..antimetal.service.agent.v1.WatchConfigRequest\x1a/.antimetal.service.agent.v1.WatchConfigResponse\"\x00(\x010\x01B\x80\x02\n" +
	"\x1ecom.antimetal.service.agent.v1B\fServiceProtoP\x01ZEgithub.com/antimetal/agent/pkg/api/antimetal/service/agent/v1;agentv1\xa2\x02\x03ASA\xaa\x02\x1aAntimetal.Service.Agent.V1\xca\x02\x1aAntimetal\\Service\\Agent\\V1\xe2\x02&Antimetal\\Service\\Agent\\V1\\GPBMetadata\xea\x02\x1dAntimetal::Service::Agent::V1b\x06proto3"

var (
	file_antimetal_service_agent_v1_service_proto_rawDescOnce sync.Once
	file_antimetal_service_agent_v1_service_proto_rawDescData []byte
)

func file_antimetal_service_agent_v1_service_proto_rawDescGZIP() []byte {
	file_antimetal_service_agent_v1_service_proto_rawDescOnce.Do(func() {
		file_antimetal_service_agent_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_antimetal_service_agent_v1_service_proto_rawDesc), len(file_antimetal_service_agent_v1_service_proto_rawDesc)))
	})
	return file_antimetal_service_agent_v1_service_proto_rawDescData
}

var file_antimetal_service_agent_v1_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_antimetal_service_agent_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_antimetal_service_agent_v1_service_proto_goTypes = []any{
	(WatchConfigRequestType)(0), // 0: antimetal.service.agent.v1.WatchConfigRequestType
	(*WatchConfigRequest)(nil),  // 1: antimetal.service.agent.v1.WatchConfigRequest
	(*WatchConfigResponse)(nil), // 2: antimetal.service.agent.v1.WatchConfigResponse
	(*v1.Instance)(nil),         // 3: antimetal.agent.v1.Instance
	(v1.Collectors)(0),          // 4: antimetal.agent.v1.Collectors
	(*v11.Object)(nil),          // 5: antimetal.types.v1.Object
	(*v12.Linux)(nil),           // 6: antimetal.runtime.v1.Linux
	(*status.Status)(nil),       // 7: google.rpc.Status
}
var file_antimetal_service_agent_v1_service_proto_depIdxs = []int32{
	3, // 0: antimetal.service.agent.v1.WatchConfigRequest.instance:type_name -> antimetal.agent.v1.Instance
	0, // 1: antimetal.service.agent.v1.WatchConfigRequest.type:type_name -> antimetal.service.agent.v1.WatchConfigRequestType
	4, // 2: antimetal.service.agent.v1.WatchConfigRequest.supported_collectors:type_name -> antimetal.agent.v1.Collectors
	5, // 3: antimetal.service.agent.v1.WatchConfigRequest.initial_configs:type_name -> antimetal.types.v1.Object
	6, // 4: antimetal.service.agent.v1.WatchConfigRequest.linux_runtime:type_name -> antimetal.runtime.v1.Linux
	7, // 5: antimetal.service.agent.v1.WatchConfigRequest.error_detail:type_name -> google.rpc.Status
	5, // 6: antimetal.service.agent.v1.WatchConfigResponse.configs:type_name -> antimetal.types.v1.Object
	1, // 7: antimetal.service.agent.v1.AgentManagementService.WatchConfig:input_type -> antimetal.service.agent.v1.WatchConfigRequest
	2, // 8: antimetal.service.agent.v1.AgentManagementService.WatchConfig:output_type -> antimetal.service.agent.v1.WatchConfigResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_antimetal_service_agent_v1_service_proto_init() }
func file_antimetal_service_agent_v1_service_proto_init() {
	if File_antimetal_service_agent_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_antimetal_service_agent_v1_service_proto_rawDesc), len(file_antimetal_service_agent_v1_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_antimetal_service_agent_v1_service_proto_goTypes,
		DependencyIndexes: file_antimetal_service_agent_v1_service_proto_depIdxs,
		EnumInfos:         file_antimetal_service_agent_v1_service_proto_enumTypes,
		MessageInfos:      file_antimetal_service_agent_v1_service_proto_msgTypes,
	}.Build()
	File_antimetal_service_agent_v1_service_proto = out.File
	file_antimetal_service_agent_v1_service_proto_goTypes = nil
	file_antimetal_service_agent_v1_service_proto_depIdxs = nil
}
