// Copyright Antimetal, Inc. All rights reserved.
//
// Use of this source code is governed by a source available license that can be found in the
// LICENSE file or at:
// https://polyformproject.org/wp-content/uploads/2020/06/PolyForm-Shield-1.0.0.txt

// Copyright 2024 Antimetal LLC
// SPDX-License-Identifier: PolyForm-Shield-1.0.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: pkg/performance/proto/profile.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProfileBatch contains efficiently-packed profiling events
// Events are binary-encoded in packed_events to maintain zero allocations
type ProfileBatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Batch collection timestamp in nanoseconds since Unix epoch
	TimestampNs uint64 `protobuf:"varint,1,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	// Number of CPUs on the system
	CpuCount uint32 `protobuf:"varint,2,opt,name=cpu_count,json=cpuCount,proto3" json:"cpu_count,omitempty"`
	// Binary-packed ProfileEvents using efficient encoding
	// Format (32 bytes per event):
	// [0:8]   uint64 timestamp_ns     - Event timestamp
	// [8:12]  int32  pid              - Process ID
	// [12:16] int32  tid              - Thread ID
	// [16:20] int32  user_stack_id    - User stack trace ID
	// [20:24] int32  kernel_stack_id  - Kernel stack trace ID
	// [24:28] uint32 cpu              - CPU number
	// [28:32] uint32 flags            - Event flags
	PackedEvents []byte `protobuf:"bytes,3,opt,name=packed_events,json=packedEvents,proto3" json:"packed_events,omitempty"`
	// Number of events in packed_events
	EventCount uint32 `protobuf:"varint,4,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`
	// Binary format version for backward compatibility
	FormatVersion uint32 `protobuf:"varint,5,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	// Number of events dropped due to buffer exhaustion
	DroppedEvents uint32 `protobuf:"varint,6,opt,name=dropped_events,json=droppedEvents,proto3" json:"dropped_events,omitempty"`
	// Optional: Node identifier for multi-node deployments
	NodeName string `protobuf:"bytes,7,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	// Optional: Additional metadata
	Metadata      map[string]string `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileBatch) Reset() {
	*x = ProfileBatch{}
	mi := &file_pkg_performance_proto_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileBatch) ProtoMessage() {}

func (x *ProfileBatch) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_performance_proto_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileBatch.ProtoReflect.Descriptor instead.
func (*ProfileBatch) Descriptor() ([]byte, []int) {
	return file_pkg_performance_proto_profile_proto_rawDescGZIP(), []int{0}
}

func (x *ProfileBatch) GetTimestampNs() uint64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *ProfileBatch) GetCpuCount() uint32 {
	if x != nil {
		return x.CpuCount
	}
	return 0
}

func (x *ProfileBatch) GetPackedEvents() []byte {
	if x != nil {
		return x.PackedEvents
	}
	return nil
}

func (x *ProfileBatch) GetEventCount() uint32 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

func (x *ProfileBatch) GetFormatVersion() uint32 {
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

func (x *ProfileBatch) GetDroppedEvents() uint32 {
	if x != nil {
		return x.DroppedEvents
	}
	return 0
}

func (x *ProfileBatch) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *ProfileBatch) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ProfileStream is used for streaming profile batches
type ProfileStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ProfileStreamRequest_Batch
	//	*ProfileStreamRequest_Handshake
	Payload       isProfileStreamRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileStreamRequest) Reset() {
	*x = ProfileStreamRequest{}
	mi := &file_pkg_performance_proto_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileStreamRequest) ProtoMessage() {}

func (x *ProfileStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_performance_proto_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileStreamRequest.ProtoReflect.Descriptor instead.
func (*ProfileStreamRequest) Descriptor() ([]byte, []int) {
	return file_pkg_performance_proto_profile_proto_rawDescGZIP(), []int{1}
}

func (x *ProfileStreamRequest) GetPayload() isProfileStreamRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ProfileStreamRequest) GetBatch() *ProfileBatch {
	if x != nil {
		if x, ok := x.Payload.(*ProfileStreamRequest_Batch); ok {
			return x.Batch
		}
	}
	return nil
}

func (x *ProfileStreamRequest) GetHandshake() *ProfileHandshake {
	if x != nil {
		if x, ok := x.Payload.(*ProfileStreamRequest_Handshake); ok {
			return x.Handshake
		}
	}
	return nil
}

type isProfileStreamRequest_Payload interface {
	isProfileStreamRequest_Payload()
}

type ProfileStreamRequest_Batch struct {
	Batch *ProfileBatch `protobuf:"bytes,1,opt,name=batch,proto3,oneof"`
}

type ProfileStreamRequest_Handshake struct {
	Handshake *ProfileHandshake `protobuf:"bytes,2,opt,name=handshake,proto3,oneof"`
}

func (*ProfileStreamRequest_Batch) isProfileStreamRequest_Payload() {}

func (*ProfileStreamRequest_Handshake) isProfileStreamRequest_Payload() {}

// ProfileHandshake establishes stream parameters
type ProfileHandshake struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Client capabilities
	SupportedFormatVersion uint32 `protobuf:"varint,1,opt,name=supported_format_version,json=supportedFormatVersion,proto3" json:"supported_format_version,omitempty"`
	// Requested sampling frequency in Hz
	SamplingFrequencyHz uint32 `protobuf:"varint,2,opt,name=sampling_frequency_hz,json=samplingFrequencyHz,proto3" json:"sampling_frequency_hz,omitempty"`
	// Client identifier
	ClientId      string `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileHandshake) Reset() {
	*x = ProfileHandshake{}
	mi := &file_pkg_performance_proto_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileHandshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileHandshake) ProtoMessage() {}

func (x *ProfileHandshake) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_performance_proto_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileHandshake.ProtoReflect.Descriptor instead.
func (*ProfileHandshake) Descriptor() ([]byte, []int) {
	return file_pkg_performance_proto_profile_proto_rawDescGZIP(), []int{2}
}

func (x *ProfileHandshake) GetSupportedFormatVersion() uint32 {
	if x != nil {
		return x.SupportedFormatVersion
	}
	return 0
}

func (x *ProfileHandshake) GetSamplingFrequencyHz() uint32 {
	if x != nil {
		return x.SamplingFrequencyHz
	}
	return 0
}

func (x *ProfileHandshake) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// ProfileStreamResponse acknowledges batches
type ProfileStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sequence number of acknowledged batch
	AckSequence uint64 `protobuf:"varint,1,opt,name=ack_sequence,json=ackSequence,proto3" json:"ack_sequence,omitempty"`
	// Server can request rate adjustment
	SuggestedRateHz uint32 `protobuf:"varint,2,opt,name=suggested_rate_hz,json=suggestedRateHz,proto3" json:"suggested_rate_hz,omitempty"`
	// Error message if any
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileStreamResponse) Reset() {
	*x = ProfileStreamResponse{}
	mi := &file_pkg_performance_proto_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileStreamResponse) ProtoMessage() {}

func (x *ProfileStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_performance_proto_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileStreamResponse.ProtoReflect.Descriptor instead.
func (*ProfileStreamResponse) Descriptor() ([]byte, []int) {
	return file_pkg_performance_proto_profile_proto_rawDescGZIP(), []int{3}
}

func (x *ProfileStreamResponse) GetAckSequence() uint64 {
	if x != nil {
		return x.AckSequence
	}
	return 0
}

func (x *ProfileStreamResponse) GetSuggestedRateHz() uint32 {
	if x != nil {
		return x.SuggestedRateHz
	}
	return 0
}

func (x *ProfileStreamResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pkg_performance_proto_profile_proto protoreflect.FileDescriptor

const file_pkg_performance_proto_profile_proto_rawDesc = "" +
	"\n" +
	"#pkg/performance/proto/profile.proto\x12\vperformance\"\x81\x03\n" +
	"\fProfileBatch\x12!\n" +
	"\ftimestamp_ns\x18\x01 \x01(\x04R\vtimestampNs\x12\x1b\n" +
	"\tcpu_count\x18\x02 \x01(\rR\bcpuCount\x12#\n" +
	"\rpacked_events\x18\x03 \x01(\fR\fpackedEvents\x12\x1f\n" +
	"\vevent_count\x18\x04 \x01(\rR\n" +
	"eventCount\x12%\n" +
	"\x0eformat_version\x18\x05 \x01(\rR\rformatVersion\x12%\n" +
	"\x0edropped_events\x18\x06 \x01(\rR\rdroppedEvents\x12\x1b\n" +
	"\tnode_name\x18\a \x01(\tR\bnodeName\x12C\n" +
	"\bmetadata\x18\b \x03(\v2'.performance.ProfileBatch.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x93\x01\n" +
	"\x14ProfileStreamRequest\x121\n" +
	"\x05batch\x18\x01 \x01(\v2\x19.performance.ProfileBatchH\x00R\x05batch\x12=\n" +
	"\thandshake\x18\x02 \x01(\v2\x1d.performance.ProfileHandshakeH\x00R\thandshakeB\t\n" +
	"\apayload\"\x9d\x01\n" +
	"\x10ProfileHandshake\x128\n" +
	"\x18supported_format_version\x18\x01 \x01(\rR\x16supportedFormatVersion\x122\n" +
	"\x15sampling_frequency_hz\x18\x02 \x01(\rR\x13samplingFrequencyHz\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\"|\n" +
	"\x15ProfileStreamResponse\x12!\n" +
	"\fack_sequence\x18\x01 \x01(\x04R\vackSequence\x12*\n" +
	"\x11suggested_rate_hz\x18\x02 \x01(\rR\x0fsuggestedRateHz\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05errorB2Z0github.com/antimetal/agent/pkg/performance/protob\x06proto3"

var (
	file_pkg_performance_proto_profile_proto_rawDescOnce sync.Once
	file_pkg_performance_proto_profile_proto_rawDescData []byte
)

func file_pkg_performance_proto_profile_proto_rawDescGZIP() []byte {
	file_pkg_performance_proto_profile_proto_rawDescOnce.Do(func() {
		file_pkg_performance_proto_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_performance_proto_profile_proto_rawDesc), len(file_pkg_performance_proto_profile_proto_rawDesc)))
	})
	return file_pkg_performance_proto_profile_proto_rawDescData
}

var file_pkg_performance_proto_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_performance_proto_profile_proto_goTypes = []any{
	(*ProfileBatch)(nil),          // 0: performance.ProfileBatch
	(*ProfileStreamRequest)(nil),  // 1: performance.ProfileStreamRequest
	(*ProfileHandshake)(nil),      // 2: performance.ProfileHandshake
	(*ProfileStreamResponse)(nil), // 3: performance.ProfileStreamResponse
	nil,                           // 4: performance.ProfileBatch.MetadataEntry
}
var file_pkg_performance_proto_profile_proto_depIdxs = []int32{
	4, // 0: performance.ProfileBatch.metadata:type_name -> performance.ProfileBatch.MetadataEntry
	0, // 1: performance.ProfileStreamRequest.batch:type_name -> performance.ProfileBatch
	2, // 2: performance.ProfileStreamRequest.handshake:type_name -> performance.ProfileHandshake
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_performance_proto_profile_proto_init() }
func file_pkg_performance_proto_profile_proto_init() {
	if File_pkg_performance_proto_profile_proto != nil {
		return
	}
	file_pkg_performance_proto_profile_proto_msgTypes[1].OneofWrappers = []any{
		(*ProfileStreamRequest_Batch)(nil),
		(*ProfileStreamRequest_Handshake)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_performance_proto_profile_proto_rawDesc), len(file_pkg_performance_proto_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_performance_proto_profile_proto_goTypes,
		DependencyIndexes: file_pkg_performance_proto_profile_proto_depIdxs,
		MessageInfos:      file_pkg_performance_proto_profile_proto_msgTypes,
	}.Build()
	File_pkg_performance_proto_profile_proto = out.File
	file_pkg_performance_proto_profile_proto_goTypes = nil
	file_pkg_performance_proto_profile_proto_depIdxs = nil
}
