name: Auto Format

# This workflow automatically formats Go and C/C++ code on pull requests.
# If formatting changes are needed, it commits and pushes them to the PR branch.

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**.go'
      - '**.c'
      - '**.h'
      - '!docs/**'
      - '!**/*.pb.go'        # Skip protobuf generated files
      - '!**/*_generated.go'  # Skip other generated files

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: auto-format-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  auto-format:
    name: Auto Format Code
    runs-on: ubuntu-latest
    # Only run on PRs from the same repository (not forks)
    # This ensures we have write access to push changes
    if: github.event.pull_request.head.repo.full_name == github.repository
    
    steps:
    - name: Checkout PR branch
      uses: actions/checkout@v4
      with:
        # Use the PR head ref to ensure we're on the correct branch
        ref: ${{ github.event.pull_request.head.ref }}
        # Use a token with write permissions (default GITHUB_TOKEN)
        token: ${{ secrets.GITHUB_TOKEN }}
        # Fetch full history for proper git operations
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
        cache: true
        cache-dependency-path: go.sum

    - name: Install clang-format
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y -qq clang-format

    - name: Check and apply formatting
      id: format-check
      run: |
        chmod +x .github/workflows/scripts/check-formatting.sh
        .github/workflows/scripts/check-formatting.sh

    - name: Commit and push changes
      if: steps.format-check.outputs.changes == 'true'
      env:
        GITHUB_HEAD_REF: ${{ github.event.pull_request.head.ref }}
      run: |
        chmod +x .github/workflows/scripts/commit-formatting.sh
        .github/workflows/scripts/commit-formatting.sh

    - name: Comment on PR about formatting
      if: steps.format-check.outputs.changes == 'true'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const comment = `🤖 **Auto-formatting applied**
          
          I've automatically formatted the code in this PR using:
          - \`make fmt.go\` for Go files
          - \`make fmt.clang\` for C/C++ files
          
          The changes have been pushed to your branch. Please pull the latest changes locally:
          \`\`\`bash
          git pull origin ${{ github.event.pull_request.head.ref }}
          \`\`\``;
          
          // Check if we've already commented about formatting
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number
          });
          
          const botComment = comments.find(comment => 
            comment.user.type === 'Bot' && 
            comment.body.includes('Auto-formatting applied')
          );
          
          if (botComment) {
            // Update existing comment
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body: comment
            });
          } else {
            // Create new comment
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: comment
            });
          }