name: Source Guard
on:
  push:
    branches: ["**"]
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: tok
        with:
          app-id: ${{ secrets.INTERNAL_DEV_TOOLS_APP_ID }}
          private-key: ${{ secrets.INTERNAL_DEV_TOOLS_APP_KEY }}
          owner: antimetal
          repositories: .github
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/checkout@v4
        with:
          repository: antimetal/.github
          token: ${{ steps.tok.outputs.token }}
          path: .source-guard
      - uses: ./.source-guard/.github/actions/guard
        with:
          slack-token: ${{ secrets.SLACK_BOT_TOKEN }}
